### ISSUE TITLE
Deprecation notices from doctrine\common 

### ISSUE THREAD

**Issue by Victor-Prodanov** [doctrine/doctrine-laminas-hydrator#11]
**Report**
Version 2.0.2

**Summary**
The Doctrine\Common\Util\Inflector class is deprecated, use Doctrine\Common\Inflector\Inflector from doctrine/inflector package instead.

**Expected behavior**
No deprecation should be triggered.

**Comment by TomHAnderson** [comment]
doctrine/common had been removed
https://github.com/doctrine/doctrine-laminas-hydrator/releases/tag/2.0.4
