### ISSUE TITLE
Wrong case of decimal and bigint

### ISSUE THREAD

**Issue by lampi87** [doctrine/doctrine-laminas-hydrator#26]
Hi everyone,

I've already create a PR for this issue but it wasn't merged or commented.
At the moment, decimal are casted as "string" this lead to errors when using strict types in php7.4

Best regards,
Alexander

**Comment by driehle** [comment]
Relates to #24

**Comment by driehle** [comment]
As pointed out in #24, the current behaviour is correct. A `bigint` must be casted to `string`, as bigint exceed PHP's int range. A `decimal` must be casted to `string` as well, as floats loose precision, while decimals don't.
